# Generated by Django 3.1.7 on 2021-03-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.developer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to='app.Developer'),
        ),
    ]
