# Generated by Django 3.1.7 on 2021-03-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210311_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='accepted_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.developer'),
        ),
    ]
