# Generated by Django 3.1.7 on 2021-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100)),
                ('siren', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
